spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/account
    driver-class-name: org.postgresql.Driver
    name: root
    password: root

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true